11 get articles topic query
Veresio/News-API pull request #10
Opened 2023-10-05 15:34 UTC by Veresio

2023-10-05 15:46 UTC, roisinoreilly requested changes
good job so far! I'd like you to update the test description for your 404 test and also add in a 400 test for an invalid topic eg. /articles?topic=12345. Once you've done that send us another PR :)

2023-10-05 15:46 UTC, roisinoreilly commented on __tests__/server.test.js
> +        body.articles.forEach((article) => {
don't forget to do a length check to avoid a false positive on this test

2023-10-05 15:46 UTC, roisinoreilly commented on __tests__/server.test.js
> +  test("should return a 404 error if there are no articles for that topic", () => {
this test description isn't really what you're testing, you're checking here that a valid but non-existent topic gives you a 404 which is correct, just update the description to be a bit clearer

2023-10-06 12:48 UTC, Pipe-Smoking-Rabbit approved these changes
Looks good, I've left two bits of feedback below. The second one is a fairly important change. Once you've made changes this can be merged to main, no need for another review ✅

2023-10-06 12:48 UTC, Pipe-Smoking-Rabbit commented on __tests__/server.test.js
> +        expect(body.articles.length).toBeGreaterThan(0);
You can be a bit more specific here, based on the test data how many articles should there be in the response ? - that is the length we would expect

2023-10-06 12:48 UTC, Pipe-Smoking-Rabbit commented on __tests__/server.test.js
> +        expect(body.message).toBe("No articles available with that topic");
If the topic _exists_ in the database then this isn't a 404, it's a `200`. The response should just be an empty array, similar to if there is an article with no comments from ticket 6

2023-10-06 12:53 UTC, merged